name: CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

env:
  DOCKER_APP_CONTEXT: ./Forecaster
  DOCKER_DOCKERFILE: ./Forecaster/Dockerfile
  DOCKER_IMAGE_NAME: forecaster:latest
  DOCKER_PROJECT_NAME: forecaster
  IMAGE_REGISTRY_URL: docker.pkg.github.com

jobs:
  test:
    name: Test project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test application
        run: |
            cd Forecaster
            dotnet test --no-restore --verbosity normal
  
  build:
    name: Build application and deploy artifact to packages
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{env.DOCKER_APP_CONTEXT}}
          file: ${{env.DOCKER_DOCKERFILE}}
          tags: ${{env.DOCKER_IMAGE_NAME}}
          outputs: type=docker,dest=/tmp/${{env.DOCKER_PROJECT_NAME}}.tar
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.DOCKER_PROJECT_NAME}}
          path: /tmp/${{env.DOCKER_PROJECT_NAME}}.tar
